config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end   
  end
  root 'todo_lists#index'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list

  validates :content, presence: true, 
  					length: {minimum: 2}

  scope :complete, -> {where ("completed_at is not null")}
  scope :incomplete, -> {where(completed_at: nil)}

  def completed?
  	!completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
	has_many :todo_items

	validates :title, presence: true
	validates :title, length: {minimum: 3}
	validates :description, presence: true
	validates :description, length: {minimum: 5}

	  def has_completed_items?
    todo_items.complete.size > 0
  end

  def has_incomplete_items?
    todo_items.incomplete.size > 0
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :find_todo_list

  def index
  end

  def new
    @todo_item = @todo_list.todo_items.new
  end

  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)
    if @todo_item.save
      flash[:success] = "Added todo list item."
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = "There was a problem adding that todo list item."
      render action: :new
    end
  end

  def edit
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def update
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.update_attributes(todo_item_params)
      flash[:success] = "Saved todo list item."
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = "That todo item could not be saved."
      render action: :edit
    end
  end
  
    def destroy
      @todo_item = @todo_list.todo_items.find(params[:id])
      if @todo_item.destroy
        flash[:success] = "Todo list item was deleted."
      else
        flash[:error] = "Todo list item coul not be deleted."
      end
      redirect_to todo_list_todo_items_path
    end


    def complete
      @todo_item = @todo_list.todo_items.find(params[:id])
      @todo_item.update_attribute(:completed_at, Time.now)
      redirect_to todo_list_todo_items_path, notice: "Todo item marked as completed"
    end

  def url_options
    { todo_list_id: params[:todo_list_id] }.merge(super)
  end

  private

  def find_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mandy's Do-it Lists</title>
  <link href='http://fonts.googleapis.com/css?family=Patrick+Hand' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="main-body">
	<div class="nav">
	<h1><%= link_to "Mandy's Do-it Lists", root_path %></h1>
	<ul>
	<li><%= link_to "Home", todo_lists_path %></li>
	<li><%= link_to "About", "" %></li>
	<li><%= link_to "Contact", "" %></li>
	</ul>
	<br class="clear">
	</div>
	
	<% flash.each do |type, message| %>
	<div class="alert flash <%= type %>">
		<%= message %>
	</div>
	<% end %>
<%= yield %>
</div>

</body>
</html>

app/views/todo_items/_form.html.erb
<% if @todo_item.errors.any? %>    

    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>


  <%= form.label :content %>
  <%= form.text_field :content %>

  <%= form.submit "Save" %>

app/views/todo_items/edit.html.erb
<h1><%= @todo_list.title %> - Editing Item</h1>
<%= form_for [@todo_list, @todo_item] do |form| %>
  <%= render partial: form %>
<% end %>

app/views/todo_items/index.html.erb
<h1><%= @todo_list.title %></h1>

  <table class="todo_items">
  <thead>
    <tr width>
      <th width="25%">Completed?</th>
      <th width="55%">Content</th>
      <th width="20%">Functions</th>
    </tr>
  </thead>
  <tbody>
  <% @todo_list.todo_items.each do |todo_item| %>
  <tr id="<%= dom_id(todo_item) %>">
    <td>
      <% if todo_item.completed? %>
        <%= todo_item.completed_at %>
      <% else %>
        <%= link_to "Mark Complete", complete_todo_list_todo_item_path(todo_item), method: :patch %>
      <% end %>
    </td>
    <td><%= todo_item.content %></td>
    <td>
      <%= link_to "Edit", edit_todo_list_todo_item_path(todo_item) %>
      <%= link_to "Delete", todo_list_todo_item_path(todo_item), method: :delete, data: { confirm: "Are you sure?" } %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>

<p>
  <%= link_to "New Do-it Item", new_todo_list_todo_item_path %>
</p>

app/views/todo_items/new.html.erb
<h1><%= @todo_list.title %> - Add Item</h1>
<%= form_for [@todo_list, @todo_item] do |form| %>
  <%= render partial: form %>
<% end %>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Do-it list</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<% @todo_lists.each do |todo_list| %>
<div class="todo_list" id="<%= dom_id(todo_list) %>">
  <h2 class="mainpage"><%= todo_list.title %></h2>
  <p><%= todo_list.description %></p>
  <ul class="functions">
    <li><%= link_to "List Items", todo_list_todo_items_path(todo_list) %></li>
    <li><%= link_to 'Show', todo_list %></li>
    <li><%= link_to 'Edit', edit_todo_list_path(todo_list) %></li>
    <li><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></li>
  </ul>
  <br class="clear" />
</div>
<% end %>

<br>

<%= link_to 'New Do-it list >>', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New Do-it list</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<h1><%= @todo_list.title %></h1>

<h3><%= @todo_list.description %></h3>

<% if @todo_list.has_incomplete_items? %>
<h2>Incomplete Items:</h2>

<ul>
  <% @todo_list.todo_items.incomplete.each do |todo_item| %>
  <li><%= todo_item.content %></li>
  <% end %>
</ul>
<% end %>

<% if @todo_list.has_completed_items? %>
<h2>Complete Items:</h2>

<ul>
  <% @todo_list.todo_items.complete.each do |todo_item| %>
  <li><%= todo_item.content %></li>
  <% end %>
</ul>
<% end %>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>